/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api.auth.sign-in'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/exercises': typeof AppExercisesRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/exercises': typeof AppExercisesRoute
  '/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sign-in' | '/exercises' | '/api/auth/callback' | '/api/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/sign-in' | '/exercises' | '/' | '/api/auth/callback' | '/api/auth/sign-in'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/exercises'
    | '/_app/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
